### PR TITLE
comment on line 16 about spread operator

### PR DESCRIPTION
**Pull request by JTorresTMP**
Testing merging to the for-review branch

### CODE REVIEW

**Comment by JTorresTMP** [comment]
I can actually just merge them, but let me send the request either way

**Review by jayedeem — CHANGES_REQUESTED** [review]
that's cool, but you need to make the 'o' in operator lowercase

**Comment by JTorresTMP** [comment]
check out the latest hash!

**Review by jayedeem — APPROVED** [review]
good stuff

**Pull request merged**
